<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h1 style="color:purple">Sample problem of predicting home price </h1>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="https://media.github.ford.com/user/40338/files/61ec00a4-3331-4e87-b515-c1f2e0317ca7" style='height:200px;width:350px'>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="https://media.github.ford.com/user/40338/files/59a6e9d6-2b05-44d9-995c-1c713cd8f350" >

Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing: Fill NA values with median value of a column**

In [4]:
df.bedrooms.mean()

4.2

In [5]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.mean())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

<img src="https://media.github.ford.com/user/40338/files/59a6e9d6-2b05-44d9-995c-1c713cd8f350" >

In [7]:
reg.coef_

array([  116.66950551, 18756.28806982, -3675.75111708])

In [ ]:
reg.intercept_

221323.00186540408

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [ ]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [ ]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [ ]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])